language: python

sudo: required
dist: trusty

python:
    - 3.6

install: 
    - pip install -r requirements.txt

script:
    - py.test -v --cov=nilsas --cov=apps --cov-report term-missing

after_success:
    - coveralls
